In [2]:
import pandas as pd

In [3]:
data =pd.read_csv("/content/twitter_training.csv", header=None)

In [4]:
data.head()

,0,1,2,3
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [5]:
data.drop([0,1], axis = 1, inplace=True)

In [6]:
data.head()

          2                                                  3
0  Positive  im getting on borderlands and i will murder yo...
1  Positive  I am coming to the borders and I will kill you...
2  Positive  im getting on borderlands and i will kill you ...
3  Positive  im coming on borderlands and i will murder you...
4  Positive  im getting on borderlands 2 and i will murder ...

In [7]:
data.rename({2:"Sentiment", 3:"Review"}, axis = 1, inplace=True)

In [8]:
data.isna().sum()

Sentiment      0
Review       161
dtype: int64

In [9]:
data.dropna(inplace=True)

In [10]:
data.isna().sum()

Sentiment    0
Review       0
dtype: int64

In [11]:
data.duplicated().sum()

np.int64(767)

In [12]:
data.drop_duplicates(inplace=True)

In [13]:
data

        Sentiment                                             Review
0        Positive  im getting on borderlands and i will murder yo...
1        Positive  I am coming to the borders and I will kill you...
2        Positive  im getting on borderlands and i will kill you ...
3        Positive  im coming on borderlands and i will murder you...
4        Positive  im getting on borderlands 2 and i will murder ...
...           ...                                                ...
15828    Negative                                                wtf
15832    Negative                                            She wtf
15834  Irrelevant  ICYMI: @BLASTDota finds sponsor in @KITKAT. . ...
15835  Irrelevant  ICYMI: @ BLASTDota finds sponsor in @ KITKAT. ...
15836  Irrelevant  ICYMI: @ BLASTDota finds a sponsor in @ KITKAT...

[14909 rows x 2 columns]

In [14]:
data.columns

Index(['Sentiment', 'Review'], dtype='object')

In [15]:
data['Sentiment'].value_counts()

Sentiment
Negative      4447
Positive      4292
Neutral       3434
Irrelevant    2736
Name: count, dtype: int64

# Preprocesssing

In [ ]:
# lower or upper
# space
# emoji
# punctuation
# stopwords

In [18]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [19]:
import nltk  #  Natural language tool kit

In [17]:
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [22]:
stopwords.words("english")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [23]:
import re  # regular exprsssion
def preprocess(text):
    text = text.lower()  # lower
    text = re.sub("\s+", " ", text)  # extra space remove ho gaye
    text = "".join([a for a in text if a not in string.punctuation])
    text = " ".join([a for a in text.split()  if a not in stopwords.words("english")])
    return text

<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_2668/3786426270.py:4: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub("\s+", " ", text)  # extra space remove ho gaye

In [24]:
data["Review"]=data["Review"].apply(preprocess)

In [25]:
data["Sentiment"].value_counts()

Sentiment
Negative      4447
Positive      4292
Neutral       3434
Irrelevant    2736
Name: count, dtype: int64

# Tokenization

In [26]:
data['Sentiment']=data['Sentiment'].map({
    "Negative"  :   0,
    "Positive"  :  1,
    "Neutral": 2,
    "Irrelevant" :3

})

In [27]:
data['Sentiment'].value_counts()

Sentiment
0    4447
1    4292
2    3434
3    2736
Name: count, dtype: int64

In [28]:
data

       Sentiment                                             Review
0              1                      im getting borderlands murder
1              1                                coming borders kill
2              1                        im getting borderlands kill
3              1                       im coming borderlands murder
4              1                    im getting borderlands 2 murder
...          ...                                                ...
15828          0                                                wtf
15832          0                                                wtf
15834          3  icymi blastdota finds sponsor kitkat look forw...
15835          3  icymi blastdota finds sponsor kitkat look forw...
15836          3  icymi blastdota finds sponsor kitkat looking f...

[14909 rows x 2 columns]

In [29]:
import tensorflow

In [30]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [31]:
tok = Tokenizer()

In [32]:
tok.fit_on_texts(data["Review"])

In [34]:
data["Review"]= tok.texts_to_sequences(data["Review"])

In [35]:
data

       Sentiment                                             Review
0              1                                  [13, 90, 3, 1290]
1              1                                   [267, 3349, 769]
2              1                                   [13, 90, 3, 769]
3              1                                 [13, 267, 3, 1290]
4              1                               [13, 90, 3, 6, 1290]
...          ...                                                ...
15828          0                                              [138]
15832          0                                              [138]
15834          3  [7860, 7861, 7862, 2840, 7863, 95, 305, 37, 78...
15835          3  [7860, 7861, 7862, 2840, 7863, 95, 305, 37, 78...
15836          3  [7860, 7861, 7862, 2840, 7863, 225, 305, 37, 7...

[14909 rows x 2 columns]

In [36]:
tok.word_index

{'game': 1,
 'amazon': 2,
 'borderlands': 3,
 'xbox': 4,
 'overwatch': 5,
 '2': 6,
 'nba2k': 7,
 'like': 8,
 '3': 9,
 'get': 10,
 'one': 11,
 'play': 12,
 'im': 13,
 'series': 14,
 'x': 15,
 'love': 16,
 'good': 17,
 'really': 18,
 'new': 19,
 'see': 20,
 'shit': 21,
 'games': 22,
 'black': 23,
 'best': 24,
 'time': 25,
 'fuck': 26,
 'still': 27,
 '’': 28,
 'war': 29,
 'fucking': 30,
 'people': 31,
 'ops': 32,
 'video': 33,
 'got': 34,
 'cold': 35,
 'dont': 36,
 'great': 37,
 '1': 38,
 'dota': 39,
 'cant': 40,
 'playing': 41,
 'much': 42,
 'day': 43,
 'rhandlerr': 44,
 'even': 45,
 'fun': 46,
 '2k': 47,
 'would': 48,
 '5': 49,
 'win': 50,
 'another': 51,
 'played': 52,
 'first': 53,
 'thank': 54,
 'today': 55,
 'make': 56,
 'bad': 57,
 'watch': 58,
 'also': 59,
 'fix': 60,
 'year': 61,
 'go': 62,
 'back': 63,
 'want': 64,
 'ever': 65,
 'man': 66,
 'know': 67,
 '4': 68,
 'going': 69,
 'wait': 70,
 'unk': 71,
 'every': 72,
 'right': 73,
 'amazing': 74,
 'italy': 75,
 'thanks': 76,
 'actually': 77,
 'free': 78,
 'chance': 79,
 'please': 80,
 'looks': 81,
 'happy': 82,
 'think': 83,
 'ive': 84,
 'never': 85,
 'team': 86,
 'already': 87,
 'dota2': 88,
 'next': 89,
 'getting': 90,
 'n2k': 91,
 'i’m': 92,
 'excited': 93,
 'stream': 94,
 'look': 95,
 'gonna': 96,
 'players': 97,
 'say': 98,
 'damn': 99,
 'made': 100,
 '100': 101,
 'ps5': 102,
 'finally': 103,
 'youtube': 104,
 'well': 105,
 'work': 106,
 'everyone': 107,
 'hate': 108,
 'need': 109,
 'last': 110,
 'guys': 111,
 'buy': 112,
 'us': 113,
 'big': 114,
 '…': 115,
 'nice': 116,
 'yall': 117,
 'try': 118,
 'ass': 119,
 'card': 120,
 'better': 121,
 'something': 122,
 'feel': 123,
 'beluba': 124,
 'u': 125,
 'ronnie2k': 126,
 'life': 127,
 'since': 128,
 'way': 129,
 'via': 130,
 'nba': 131,
 'favorite': 132,
 'it’s': 133,
 'com': 134,
 'call': 135,
 'e': 136,
 'always': 137,
 'wtf': 138,
 'pc': 139,
 'cool': 140,
 'money': 141,
 'playoverwatch': 142,
 'could': 143,
 'gift': 144,
 'days': 145,
 'come': 146,
 'https': 147,
 'miss': 148,
 '10': 149,
 'lol': 150,
 'exciting': 151,
 'live': 152,
 'things': 153,
 'old': 154,
 'interesting': 155,
 'stop': 156,
 'pictwittercom': 157,
 'thing': 158,
 'pretty': 159,
 'doesnt': 160,
 'console': 161,
 'hell': 162,
 'take': 163,
 'unit': 164,
 'done': 165,
 'show': 166,
 'retweet': 167,
 'nba2kmyteam': 168,
 'thats': 169,
 'luck': 170,
 'community': 171,
 'awesome': 172,
 'night': 173,
 'super': 174,
 'many': 175,
 'two': 176,
 'years': 177,
 'anything': 178,
 'literally': 179,
 'summoners': 180,
 'news': 181,
 'real': 182,
 'probably': 183,
 'online': 184,
 'keep': 185,
 '2020': 186,
 'hope': 187,
 'gaming': 188,
 'rewards': 189,
 'stupid': 190,
 'grand': 191,
 'ps4': 192,
 'guy': 193,
 'myteam': 194,
 'wont': 195,
 'whole': 196,
 'world': 197,
 'gameplay': 198,
 'give': 199,
 'help': 200,
 'hours': 201,
 'sure': 202,
 'cod': 203,
 'can’t': 204,
 'lot': 205,
 'season': 206,
 'making': 207,
 'hard': 208,
 'someone': 209,
 'beta': 210,
 'little': 211,
 'makes': 212,
 'find': 213,
 'playstation': 214,
 'duty': 215,
 'quiz': 216,
 'tco': 217,
 'trash': 218,
 'player': 219,
 'wow': 220,
 '20': 221,
 'trying': 222,
 'prime': 223,
 'ill': 224,
 'looking': 225,
 'switch': 226,
 'use': 227,
 'else': 228,
 'open': 229,
 'oh': 230,
 'worth': 231,
 'nothing': 232,
 'microsoft': 233,
 'yet': 234,
 'top': 235,
 'support': 236,
 'y’all': 237,
 'order': 238,
 'check': 239,
 'beautiful': 240,
 'entering': 241,
 'book': 242,
 'global': 243,
 'tonight': 244,
 'worst': 245,
 'long': 246,
 'anyone': 247,
 'around': 248,
 'let': 249,
 'read': 250,
 'dlc': 251,
 'god': 252,
 'everything': 253,
 'wrong': 254,
 'v': 255,
 'store': 256,
 'stuff': 257,
 'league': 258,
 'w': 259,
 'epic': 260,
 'tell': 261,
 'honestly': 262,
 'shot': 263,
 'start': 264,
 'though': 265,
 'yu': 266,
 'coming': 267,
 'definitely': 268,
 'watching': 269,
 'music': 270,
 'streaming': 271,
 'end': 272,
 'times': 273,
 'care': 274,
 'don’t': 275,
 'gen': 276,
 'gs': 277,
 'price': 278,
 'story': 279,
 'launch': 280,
 'hey': 281,
 'went': 282,
 'lets': 283,
 'skin': 284,
 'away': 285,
 'working': 286,
 'uk': 287,
 'huge': 288,
 'almost': 289,
 'week': 290,
 'servers': 291,
 'deal': 292,
 'without': 293,
 'pa': 294,
 'hero': 295,
 'update': 296,
 'part': 297,
 'graphics': 298,
 'event': 299,
 'problem': 300,
 'point': 301,
 'bought': 302,
 'release': 303,
 'bit': 304,
 'forward': 305,
 'crazy': 306,
 'casey': 307,
 'able': 308,
 'treyarch': 309,
 'tomorrow': 310,
 'yes': 311,
 'absolutely': 312,
 'system': 313,
 'gets': 314,
 'seems': 315,
 'weekend': 316,
 'content': 317,
 'feels': 318,
 'funny': 319,
 'using': 320,
 'soon': 321,
 '2ksupport': 322,
 'vc': 323,
 'enjoy': 324,
 'gearboxofficial': 325,
 'seeing': 326,
 'perfect': 327,
 'moments': 328,
 'mode': 329,
 'second': 330,
 'started': 331,
 'dude': 332,
 'bro': 333,
 'sometimes': 334,
 'google': 335,
 'maybe': 336,
 'idea': 337,
 'full': 338,
 'yo': 339,
 'together': 340,
 'pay': 341,
 'broken': 342,
 'kinda': 343,
 'character': 344,
 'comes': 345,
 'shooting': 346,
 'might': 347,
 'early': 348,
 'far': 349,
 'friend': 350,
 'remember': 351,
 'mad': 352,
 'change': 353,
 'everyday': 354,
 'sorry': 355,
 'set': 356,
 'hyped': 357,
 'months': 358,
 'month': 359,
 'movie': 360,
 'said': 361,
 'may': 362,
 'mean': 363,
 'share': 364,
 'powerful': 365,
 'legendary': 366,
 'smh': 367,
 'ball': 368,
 'terrible': 369,
 'didnt': 370,
 'hit': 371,
 'buying': 372,
 'needs': 373,
 'pass': 374,
 'high': 375,
 '7': 376,
 'half': 377,
 '•': 378,
 'different': 379,
 'instead': 380,
 'pick': 381,
 'fantastic': 382,
 'dead': 383,
 'worse': 384,
 'campaign': 385,
 'sick': 386,
 'pro': 387,
 'enjoyed': 388,
 'enough': 389,
 'box': 390,
 'fan': 391,
 'drop': 392,
 'twitchtv': 393,
 'reason': 394,
 'latest': 395,
 'access': 396,
 'wanna': 397,
 'characters': 398,
 'fans': 399,
 'understand': 400,
 'bruh': 401,
 'amazonin': 402,
 'called': 403,
 'less': 404,
 'lost': 405,
 'greatest': 406,
 'toxic': 407,
 'i’ve': 408,
 'saying': 409,
 'ok': 410,
 'home': 411,
 'thought': 412,
 'valve': 413,
 'came': 414,
 'modern': 415,
 'patch': 416,
 'holy': 417,
 'cause': 418,
 'match': 419,
 'zombies': 420,
 'within': 421,
 'must': 422,
 'least': 423,
 'sucks': 424,
 'starting': 425,
 'lmao': 426,
 'congratulations': 427,
 'tried': 428,
 '15': 429,
 'used': 430,
 'edition': 431,
 'franchise': 432,
 'punch': 433,
 'seen': 434,
 'entire': 435,
 'follow': 436,
 'bc': 437,
 'kind': 438,
 '8': 439,
 'twitch': 440,
 'id': 441,
 'delivery': 442,
 'run': 443,
 'put': 444,
 'anymore': 445,
 'tv': 446,
 'left': 447,
 'current': 448,
 'wish': 449,
 'seriously': 450,
 'fast': 451,
 'says': 452,
 'level': 453,
 'face': 454,
 'theyre': 455,
 'official': 456,
 'glad': 457,
 'steam': 458,
 'giving': 459,
 'list': 460,
 'trailer': 461,
 'ago': 462,
 'simple': 463,
 'bitch': 464,
 'running': 465,
 'place': 466,
 'sony': 467,
 'hot': 468,
 'finished': 469,
 'pls': 470,
 'annoying': 471,
 'due': 472,
 'business': 473,
 'class': 474,
 'theres': 475,
 '30': 476,
 '0': 477,
 'major': 478,
 'problems': 479,
 'code': 480,
 'review': 481,
 'waiting': 482,
 'park': 483,
 'happen': 484,
 'twitter': 485,
 'kobe': 486,
 '6': 487,
 'die': 488,
 'youre': 489,
 'cute': 490,
 'f': 491,
 'complete': 492,
 'bed': 493,
 'whats': 494,
 'suck': 495,
 'hype': 496,
 'loot': 497,
 'taking': 498,
 'girl': 499,
 'r': 500,
 'collection': 501,
 'behind': 502,
 'ya': 503,
 'link': 504,
 'reddit': 505,
 'easy': 506,
 'forever': 507,
 'final': 508,
 'found': 509,
 'guess': 510,
 'name': 511,
 'consoles': 512,
 'proud': 513,
 'mayhem': 514,
 'ridiculous': 515,
 'callofduty': 516,
 'rn': 517,
 'sea': 518,
 'tho': 519,
 'break': 520,
 'sad': 521,
 'spend': 522,
 'fact': 523,
 'okay': 524,
 'welcome': 525,
 'paid': 526,
 'fall': 527,
 'gotta': 528,
 'yesterday': 529,
 'talking': 530,
 'design': 531,
 'skins': 532,
 'banned': 533,
 'performance': 534,
 'ordered': 535,
 'minutes': 536,
 'og': 537,
 'esports': 538,
 'original': 539,
 'hes': 540,
 'took': 541,
 '12': 542,
 'birthday': 543,
 'person': 544,
 'videos': 545,
 'daily': 546,
 'gamers': 547,
 'shows': 548,
 'side': 549,
 'havent': 550,
 'fire': 551,
 'warfare': 552,
 'vs': 553,
 'later': 554,
 'youtu': 555,
 'golden': 556,
 'incredible': 557,
 'bring': 558,
 'fps': 559,
 'missing': 560,
 'basketball': 561,
 'crap': 562,
 'dumb': 563,
 'possible': 564,
 'loved': 565,
 'social': 566,
 'jeff': 567,
 'market': 568,
 'piece': 569,
 'single': 570,
 'gone': 571,
 'spent': 572,
 'hour': 573,
 'talk': 574,
 'computer': 575,
 'picwikipediaorg': 576,
 'continue': 577,
 'media': 578,
 'death': 579,
 'weird': 580,
 'killing': 581,
 'handsome': 582,
 'biggest': 583,
 'late': 584,
 'true': 585,
 'hi': 586,
 'hear': 587,
 'garbage': 588,
 'friends': 589,
 'hello': 590,
 'ready': 591,
 'that’s': 592,
 'evil': 593,
 'multiplayer': 594,
 'bullshit': 595,
 'leaked': 596,
 'sale': 597,
 'ban': 598,
 'decided': 599,
 'border': 600,
 'three': 601,
 'halo': 602,
 'plays': 603,
 'controller': 604,
 'recommend': 605,
 'winning': 606,
 'mercy': 607,
 'omg': 608,
 'deals': 609,
 'exactly': 610,
 'beyond': 611,
 'dope': 612,
 'company': 613,
 'boy': 614,
 'cannot': 615,
 'jump': 616,
 'fucked': 617,
 'tracer': 618,
 'ron2k': 619,
 '9': 620,
 'shitty': 621,
 'digital': 622,
 'actual': 623,
 'green': 624,
 'moment': 625,
 'line': 626,
 'extremely': 627,
 'imagine': 628,
 'small': 629,
 'quite': 630,
 'either': 631,
 'echo': 632,
 'random': 633,
 'stay': 634,
 'forgot': 635,
 'takes': 636,
 'shoutout': 637,
 '2k21': 638,
 'taken': 639,
 'mind': 640,
 'group': 641,
 'believe': 642,
 'feeling': 643,
 'lose': 644,
 'n': 645,
 'alone': 646,
 'school': 647,
 'opinion': 648,
 'app': 649,
 'selling': 650,
 'account': 651,
 'move': 652,
 'tweet': 653,
 'developers': 654,
 'sold': 655,
 'hakusho': 656,
 'customers': 657,
 'morning': 658,
 'past': 659,
 'sound': 660,
 'short': 661,
 'wonderful': 662,
 'power': 663,
 'ranked': 664,
 'favourite': 665,
 'ps': 666,
 'c': 667,
 'voice': 668,
 'excellent': 669,
 'party': 670,
 'giveaway': 671,
 'decent': 672,
 'truly': 673,
 'number': 674,
 'disappointed': 675,
 'teams': 676,
 'warzone': 677,
 'listen': 678,
 'quit': 679,
 'strong': 680,
 'channel': 681,
 'tired': 682,
 'heart': 683,
 'song': 684,
 'history': 685,
 'sense': 686,
 'ow': 687,
 'ppl': 688,
 'sell': 689,
 'brand': 690,
 'wanted': 691,
 'totally': 692,
 'post': 693,
 'boys': 694,
 'b': 695,
 'quick': 696,
 'preorder': 697,
 'fable': 698,
 'fine': 699,
 'enter': 700,
 'four': 701,
 'whos': 702,
 'absolute': 703,
 'add': 704,
 'available': 705,
 'bitly': 706,
 'version': 707,
 'properly': 708,
 'package': 709,
 'email': 710,
 'young': 711,
 'bezos': 712,
 'p': 713,
 'ly': 714,
 'turn': 715,
 'brought': 716,
 'currently': 717,
 'wall': 718,
 'enjoying': 719,
 'others': 720,
 'yeah': 721,
 'cover': 722,
 'killed': 723,
 'service': 724,
 '50': 725,
 'highly': 726,
 'battle': 727,
 'shoot': 728,
 'completely': 729,
 'isnt': 730,
 'loving': 731,
 'internet': 732,
 'boss': 733,
 'ultimate': 734,
 'special': 735,
 '19': 736,
 'copy': 737,
 'cheap': 738,
 'missed': 739,
 'source': 740,
 'job': 741,
 'showing': 742,
 'pain': 743,
 'cuz': 744,
 'kamuy': 745,
 'amazoncom': 746,
 'apple': 747,
 'men': 748,
 'queen': 749,
 'heres': 750,
 'action': 751,
 'needed': 752,
 'crashes': 753,
 'runs': 754,
 'gold': 755,
 'beat': 756,
 'happened': 757,
 'film': 758,
 'usually': 759,
 'l': 760,
 'gave': 761,
 'somehow': 762,
 'especially': 763,
 'fit': 764,
 'gotten': 765,
 'unless': 766,
 'fake': 767,
 'cards': 768,
 'kill': 769,
 'experience': 770,
 'heard': 771,
 'total': 772,
 'despite': 773,
 'turned': 774,
 'grind': 775,
 'weapons': 776,
 'plus': 777,
 'stars': 778,
 'issues': 779,
 'screen': 780,
 'picfacebookcom': 781,
 'anyway': 782,
 'cosplay': 783,
 'squad': 784,
 'simply': 785,
 'lit': 786,
 'hold': 787,
 'sit': 788,
 '60': 789,
 'congrats': 790,
 'fight': 791,
 'dying': 792,
 'credit': 793,
 'apparently': 794,
 'expensive': 795,
 'deliver': 796,
 'ana': 797,
 'fridge': 798,
 'hair': 799,
 'horrible': 800,
 'appreciate': 801,
 'works': 802,
 'psycho': 803,
 'happening': 804,
 'duvalmagic': 805,
 'lately': 806,
 '“': 807,
 '”': 808,
 'except': 809,
 'stick': 810,
 'matter': 811,
 'july': 812,
 'ticket': 813,
 'movement': 814,
 'plz': 815,
 'watched': 816,
 'ima': 817,
 'career': 818,
 'data': 819,
 'ld2k': 820,
 'couple': 821,
 'compared': 822,
 'finish': 823,
 'chat': 824,
 'thinking': 825,
 'hand': 826,
 'normal': 827,
 'art': 828,
 'fresh': 829,
 '2018': 830,
 'minecraft': 831,
 'head': 832,
 'mistake': 833,
 'sounds': 834,
 'issue': 835,
 'join': 836,
 'choice': 837,
 'recent': 838,
 'reveal': 839,
 'sniping': 840,
 'lucky': 841,
 'cheating': 842,
 'dp': 843,
 'items': 844,
 'shipping': 845,
 'alexa': 846,
 '2k20': 847,
 'gearbox': 848,
 'added': 849,
 'option': 850,
 'send': 851,
 'fantasy': 852,
 'king': 853,
 'gun': 854,
 'save': 855,
 'lord': 856,
 'whatever': 857,
 'delayed': 858,
 'angry': 859,
 '\u200d': 860,
 'shut': 861,
 'november': 862,
 'features': 863,
 'ad': 864,
 'freaking': 865,
 'throw': 866,
 'low': 867,
 'products': 868,
 'grab': 869,
 'dollars': 870,
 'diamond': 871,
 'haven’t': 872,
 'mobile': 873,
 'guns': 874,
 'leave': 875,
 'sent': 876,
 'idk': 877,
 'dream': 878,
 'dark': 879,
 'insane': 880,
 '21': 881,
 'participating': 882,
 'weeks': 883,
 'reading': 884,
 'told': 885,
 'saw': 886,
 'lie': 887,
 'delete': 888,
 'niggas': 889,
 'brain': 890,
 'exclusives': 891,
 'meet': 892,
 'bioshock': 893,
 'rest': 894,
 'public': 895,
 'certainly': 896,
 'bl3': 897,
 'important': 898,
 'difficult': 899,
 'wouldnt': 900,
 'tchtv': 901,
 'along': 902,
 'ur': 903,
 'kids': 904,
 'based': 905,
 'become': 906,
 '360': 907,
 'middle': 908,
 'inside': 909,
 'type': 910,
 'updates': 911,
 'devs': 912,
 'goddamn': 913,
 'exclusive': 914,
 'amazons': 915,
 'podcast': 916,
 'process': 917,
 'comp': 918,
 'respect': 919,
 'de': 920,
 'anywhere': 921,
 'loves': 922,
 '–': 923,
 'officially': 924,
 'etc': 925,
 'cross': 926,
 'software': 927,
 'constantly': 928,
 'lego': 929,
 'delay': 930,
 'episode': 931,
 'knowing': 932,
 'goes': 933,
 'loss': 934,
 'score': 935,
 'popular': 936,
 'losing': 937,
 'sports': 938,
 'response': 939,
 'folks': 940,
 'boring': 941,
 'mw': 942,
 'dog': 943,
 'setting': 944,
 'potential': 945,
 'till': 946,
 'wifi': 947,
 'police': 948,
 'scam': 949,
 'xboxp3': 950,
 'shout': 951,
 'space': 952,
 'quality': 953,
 'production': 954,
 'blood': 955,
 'tournament': 956,
 'quickly': 957,
 '13': 958,
 'sub': 959,
 'casting': 960,
 'master': 961,
 'eu': 962,
 'randy': 963,
 'pitchford': 964,
 'safe': 965,
 'shame': 966,
 'couldnt': 967,
 'worlds': 968,
 'control': 969,
 'doom': 970,
 'means': 971,
 'ti': 972,
 'trump': 973,
 'dear': 974,
 'tf': 975,
 'atviassist': 976,
 'rt': 977,
 'idc': 978,
 'broke': 979,
 'incredibly': 980,
 '2nd': 981,
 'coolest': 982,
 'grateful': 983,
 'ask': 984,
 'dick': 985,
 'cancel': 986,
 'smart': 987,
 'preorders': 988,
 'winners': 989,
 'legends': 990,
 'nextgen': 991,
 'streamer': 992,
 'looked': 993,
 'room': 994,
 'brilliant': 995,
 '11': 996,
 'close': 997,
 'fandom': 998,
 'mission': 999,
 'gay': 1000,
 ...}

In [37]:
data

       Sentiment                                             Review
0              1                                  [13, 90, 3, 1290]
1              1                                   [267, 3349, 769]
2              1                                   [13, 90, 3, 769]
3              1                                 [13, 267, 3, 1290]
4              1                               [13, 90, 3, 6, 1290]
...          ...                                                ...
15828          0                                              [138]
15832          0                                              [138]
15834          3  [7860, 7861, 7862, 2840, 7863, 95, 305, 37, 78...
15835          3  [7860, 7861, 7862, 2840, 7863, 95, 305, 37, 78...
15836          3  [7860, 7861, 7862, 2840, 7863, 225, 305, 37, 7...

[14909 rows x 2 columns]

In [40]:
max([len(a) for a in data["Review"]])

163

# Paddding

In [38]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [44]:
X=pad_sequences(data["Review"], maxlen=163, padding="post")

In [45]:
y=data["Sentiment"]
y.value_counts()

Sentiment
0    4447
1    4292
2    3434
3    2736
Name: count, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.25, random_state=42)

In [47]:
from tensorflow.keras import layers
from tensorflow import keras

In [52]:
vocab_size = len(tok.word_index) + 1

In [ ]:
stacked rnn

In [ ]:
# rnn

In [72]:
# 2. Build the model with an Embedding layer
model = keras.Sequential([
    layers.Embedding(input_dim=vocab_size, output_dim=128, input_length=163),
    layers.SimpleRNN(128, activation="relu", return_sequences=False),
    #layers.SimpleRNN(128, activation="relu", return_sequences=False),
    layers.Dense(4, activation="softmax")
])

In [73]:
# 3. Compile the model
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [74]:
# 5. Fit the model using validation_data as a tuple
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)

Epoch 1/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 10s 21ms/step - accuracy: 0.2907 - loss: 1.3719 - val_accuracy: 0.2953 - val_loss: 1.3670
Epoch 2/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.2912 - loss: 1.3706 - val_accuracy: 0.2967 - val_loss: 1.3677
Epoch 3/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.2900 - loss: 1.3707 - val_accuracy: 0.2967 - val_loss: 1.3672
Epoch 4/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.2971 - loss: 1.5546 - val_accuracy: 0.2967 - val_loss: 1.3688
Epoch 5/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.2945 - loss: 1.3712 - val_accuracy: 0.2967 - val_loss: 1.3679
Epoch 6/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.2964 - loss: 1.3706 - val_accuracy: 0.2967 - val_loss: 1.3672
Epoch 7/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.2941 - loss: 1.3702 - val_accuracy: 0.2967 - val_loss: 1.3697
Epoch 8/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.2958 - loss: 1.3706 - val_accuracy: 0.2953 - val_loss: 1.3664
Epoch 9/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.2976 - loss: 1.3704 - val_accuracy: 0.2967 - val_loss: 1.3673
Epoch 10/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.2968 - loss: 1.3779 - val_accuracy: 0.2967 - val_loss: 1.3669

In [ ]:
#lstm

In [75]:
# 2. Build the model with an Embedding layer
model = keras.Sequential([
    layers.Embedding(input_dim=vocab_size, output_dim=128, input_length=163),
    layers.LSTM(128, activation="relu", return_sequences=False),
    layers.Dense(4, activation="softmax")
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [76]:
# 3. Compile the model
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [77]:
# 5. Fit the model using validation_data as a tuple
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)

Epoch 1/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.2934 - loss: 1.3716 - val_accuracy: 0.2967 - val_loss: 1.3693
Epoch 2/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 7s 20ms/step - accuracy: 0.2973 - loss: 1.3703 - val_accuracy: 0.2967 - val_loss: 1.3700
Epoch 3/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 7s 20ms/step - accuracy: 0.3005 - loss: 1.3702 - val_accuracy: 0.2967 - val_loss: 1.3673
Epoch 4/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 7s 20ms/step - accuracy: 0.2963 - loss: 1.3704 - val_accuracy: 0.2967 - val_loss: 1.3669
Epoch 5/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 7s 19ms/step - accuracy: 0.2977 - loss: 1.3698 - val_accuracy: 0.2967 - val_loss: 1.3669
Epoch 6/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 7s 20ms/step - accuracy: 0.2989 - loss: 1.3697 - val_accuracy: 0.2967 - val_loss: 1.3666
Epoch 7/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 7s 19ms/step - accuracy: 0.2993 - loss: 1.3702 - val_accuracy: 0.2967 - val_loss: 1.3665
Epoch 8/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 7s 20ms/step - accuracy: 0.2976 - loss: 1.3697 - val_accuracy: 0.2967 - val_loss: 1.3665
Epoch 9/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 9s 25ms/step - accuracy: 0.2989 - loss: 1.3698 - val_accuracy: 0.2967 - val_loss: 1.3666
Epoch 10/10
350/350 ━━━━━━━━━━━━━━━━━━━━ 8s 22ms/step - accuracy: 0.2989 - loss: 1.3697 - val_accuracy: 0.2967 - val_loss: 1.3667

In [ ]:
# gru

In [78]:
# 2. Build the model with an Embedding layer
model = keras.Sequential([
    layers.Embedding(input_dim=vocab_size, output_dim=128, input_length=163),
    layers.GRU(128, activation="relu", return_sequences=False),
    layers.Dense(4, activation="softmax")
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [79]:
# 3. Compile the model
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
# 5. Fit the model using validation_data as a tuple
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    validation_data=(X_test, y_test)
)

Epoch 1/10
132/350 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - accuracy: 0.2952 - loss: 1.3777