In [33]:
import pandas as pd

In [34]:
df = pd.read_csv('student_habits_performance.csv')
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [35]:
df.isna().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
numeric_data = df.select_dtypes(include='number')
other_data = df.select_dtypes(include='object')

/tmp/ipykernel_47811/3756075225.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  other_data = df.select_dtypes(include='object')

In [38]:
numeric_data
other_data

,student_id,gender,part_time_job,diet_quality,parental_education_level,internet_quality,extracurricular_participation
0,S1000,Female,No,Fair,Master,Average,Yes
1,S1001,Female,No,Good,High School,Average,No
2,S1002,Male,No,Poor,High School,Poor,No
3,S1003,Female,No,Poor,Master,Good,Yes
4,S1004,Female,No,Fair,Master,Good,No
...,...,...,...,...,...,...,...
995,S1995,Female,No,Fair,High School,Good,Yes
996,S1996,Female,Yes,Poor,High School,Average,Yes
997,S1997,Male,No,Good,Bachelor,Good,Yes
998,S1998,Male,Yes,Fair,Bachelor,Average,No
999,S1999,Female,No,Good,Bachelor,Average,No

In [39]:
x = numeric_data.drop('exam_score',axis=1)
y = numeric_data['exam_score']
x.head()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating
0,23,0.0,1.2,1.1,85.0,8.0,6,8
1,20,6.9,2.8,2.3,97.3,4.6,6,8
2,21,1.4,3.1,1.3,94.8,8.0,1,1
3,23,1.0,3.9,1.0,71.0,9.2,4,1
4,19,5.0,4.4,0.5,90.9,4.9,3,1

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.30,random_state=42)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("Y_train:", Y_train.shape)
print("Y_test:", Y_test.shape)

X_train: (700, 8)
X_test: (300, 8)
Y_train: (700,)
Y_test: (300,)

In [41]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,Y_train)

LinearRegression()

In [42]:
lr.score(X_train,Y_train)

0.9010117069230436

In [43]:
Y_train_pred = lr.predict(X_train)
Y_test_pred = lr.predict(X_test)

In [44]:
results = pd.DataFrame(
   { 
    "Actual" : Y_test.values,
    "Predicted" : Y_test_pred
    }
)

In [45]:
results

     Actual  Predicted
0      64.2  66.438797
1      72.7  74.824270
2      79.0  78.422311
3      79.5  74.603377
4      58.2  61.524044
..      ...        ...
295    66.8  65.354402
296    62.0  59.474289
297    52.4  53.028067
298    72.6  77.065112
299    57.3  55.588303

[300 rows x 2 columns]

In [46]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
train_mae = mean_absolute_error(Y_train, Y_train_pred)
train_mse = mean_squared_error(Y_train, Y_train_pred)
train_rmse = train_mse ** 0.5  
train_r2 = r2_score(Y_train, Y_train_pred)
print("TRAIN performance")
print("MAE :", train_mae)
print("MSE :", train_mse)
print("RMSE:", train_rmse)
print("R2  :", train_r2)

TRAIN performance
MAE : 4.219233116263185
MSE : 28.484520213438586
RMSE: 5.337089114249319
R2  : 0.9010117069230436

In [48]:
test_mae = mean_absolute_error(Y_test, Y_test_pred)
test_mse = mean_squared_error(Y_test, Y_test_pred)
test_rmse = test_mse ** 0.5
test_r2 = r2_score(Y_test, Y_test_pred)

print("TEST performance")
print("MAE :", test_mae)
print("MSE :", test_mse)
print("RMSE:", test_rmse)
print("R2  :", test_r2)

TEST performance
MAE : 4.229445241943834
MSE : 28.2331847309418
RMSE: 5.313490823455123
R2  : 0.8983545515482991

In [49]:
lr.coef_

array([ 0.06960354,  9.59188927, -2.74450869, -2.37359222,  0.1459774 ,
        2.02307756,  1.27787585,  1.94070414])

In [50]:
lr.intercept_

np.float64(5.67577289251625)